BachelorProject/Models/LogRecord.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BachelorProject.Models
{
    public class LogRecord
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        //fk
        [ForeignKey("ApplicationUser")]
        public string UserId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }

        [DataType(DataType.DateTime)]        
        public DateTime DateOfRecord { get; set; }
        public LogAction Action { get; set; }
        public string InfoMessage { get; set; }

    }
}

public enum LogAction
{
    FORBRUK,
    NYTT_UTSTYR,
    ENDRING,
    SLETTING
}

BachelorProject/Controllers/LogRecordsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BachelorProject.Models;
using PagedList; //pagination: ToPagedList()
using PagedList.EntityFramework; // pagination async: ToPagedListAsync()
using Microsoft.AspNet.Identity;

namespace BachelorProject.Controllers
{
    [Authorize]
    public class LogRecordsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: LogRecords
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Index()
        {
            var logRecords = db.LogRecords.Include(r => r.ApplicationUser);

            ViewBag.searchParameter = "";

            int pageSize = 10;
            int pageNumber = 1;
            return View(await logRecords.OrderByDescending(record => record.Id).ToPagedListAsync(pageNumber, pageSize));
        }

        [Authorize(Roles = "worker,subAdmin")]
        public async Task<ActionResult> IndexByUserId()
        {
            try
            {
                if (!User.Identity.IsAuthenticated)
                {
                    throw new NotImplementedException();
                }

                string userId = User.Identity.GetUserId();

                int pageNumber = 1;
                int pageSize = 10;

                var result = db.LogRecords.Include(r => r.ApplicationUser)
                                           .Where(d => d.ApplicationUser.Id == userId);

                var viewResult = await result.OrderByDescending(r => r.Id)
                                             .ToPagedListAsync(pageNumber, pageSize);
                return View("IndexByUserId", viewResult as IEnumerable<LogRecord>);
            }
            catch (Exception e)
            {
                //var msg = e.Message;
                throw new NotImplementedException();
            }
        }

        [Authorize(Roles = "worker,subAdmin")]
        public async Task<ActionResult> UpdateIndexByUserId(string searchParameter, int? page, string sortColumn, string sortOrder)
        {
            try
            {
                if (!User.Identity.IsAuthenticated)
                {
                    throw new NotImplementedException();
                }

                string userId = User.Identity.GetUserId();

                int pageNumber = (page ?? 1);
                int pageSize = 10;

                var result = db.LogRecords.Include(r => r.ApplicationUser)
                                           .Where(d => d.ApplicationUser.Id == userId);

                //filtering the query
                if (searchParameter != null && searchParameter != "")
                {
                    ViewBag.searchParameter = searchParameter;
                    result = result.Where(d => d.InfoMessage.Contains(searchParameter));
                }

                //sorting the query
                ViewBag.sortColumn = sortColumn; //this can be null
                ViewBag.sortOrder = sortOrder; //this can be null
                switch (sortColumn)
                {
                    case "DateOfRecord":
                        if (sortOrder == "ASC")
                        {
                            result = result.OrderBy(d => d.DateOfRecord);
                            ViewBag.newSortOrderForDateOfRecord = "DESC";
                        }
                        else
                        {
                            result = result.OrderByDescending(d => d.DateOfRecord);
                            ViewBag.newSortOrderForDateOfRecord = "ASC";
                        }
                        break;
                    case "Action":
                        if (sortOrder == "ASC")
                        {
                            result = result.OrderBy(d => d.Action);
                            ViewBag.newSortOrderForAction = "DESC";
                        }
                        else
                        {
                            result = result.OrderByDescending(d => d.Action);
                            ViewBag.newSortOrderForAction = "ASC";
                        }
                        break;
                    case "InfoMessage":
                        if (sortOrder == "ASC")
                        {
                            result = result.OrderBy(d => d.InfoMessage);
                            ViewBag.newSortOrderForInfoMessage = "DESC";
                        }
                        else
                        {
                            result = result.OrderByDescending(d => d.InfoMessage);
                            ViewBag.newSortOrderForInfoMessage = "ASC";
                        }
                        break;
                    default:
                        result = result.OrderBy(s => s.Id);
                        break;
                }


                var viewResult = await result.ToPagedListAsync(pageNumber, pageSize);
                return PartialView("UpdateIndexByUserId", viewResult as IEnumerable<LogRecord>);
            }
            catch (Exception e)
            {
                throw new Exception();
            }
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> UpdateIndex(string searchParameter, int? page, string sortColumn, string sortOrder)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;

            IQueryable<LogRecord> result;

            //filtering the query
            if (searchParameter != null && searchParameter != "")
            {
                ViewBag.searchParameter = searchParameter;
                result = db.LogRecords
                           .Include(r => r.ApplicationUser)
                            //filter
                            .Where(d => d.ApplicationUser.Email.Contains(searchParameter) ||
                                            d.ApplicationUser.FirstName.Contains(searchParameter) ||
                                            d.ApplicationUser.LastName.Contains(searchParameter));
            }
            else
            {
                //searchParameter is null, i.e. no filter is specified
                result = db.LogRecords.Include(r => r.ApplicationUser);
            }

            //sorting the query
            ViewBag.sortColumn = sortColumn; //this can be null
            ViewBag.sortOrder = sortOrder; //this can be null
            switch (sortColumn)
            {
                case "FirstName":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.ApplicationUser.FirstName);
                        ViewBag.newSortOrderForFirstName = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.ApplicationUser.FirstName);
                        ViewBag.newSortOrderForFirstName = "ASC";
                    }
                    break;
                case "LastName":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.ApplicationUser.LastName);
                        ViewBag.newSortOrderForLastName = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.ApplicationUser.LastName);
                        ViewBag.newSortOrderForLastName = "ASC";
                    }
                    break;
                case "Email":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.ApplicationUser.Email);
                        ViewBag.newSortOrderForEmail = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.ApplicationUser.Email);
                        ViewBag.newSortOrderForEmail = "ASC";
                    }
                    break;
                case "DateOfRecord":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.DateOfRecord);
                        ViewBag.newSortOrderForDateOfRecord = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.DateOfRecord);
                        ViewBag.newSortOrderForDateOfRecord = "ASC";
                    }
                    break;
                case "Action":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.Action);
                        ViewBag.newSortOrderForAction = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.Action);
                        ViewBag.newSortOrderForAction = "ASC";
                    }
                    break;
                case "InfoMessage":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.InfoMessage);
                        ViewBag.newSortOrderForInfoMessage = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.InfoMessage);
                        ViewBag.newSortOrderForInfoMessage = "ASC";
                    }
                    break;
                default:
                    result = result.OrderBy(s => s.Id);
                    break;
            }


            var viewResult = await result.ToPagedListAsync(pageNumber, pageSize);
            return PartialView("UpdateIndex", viewResult as IEnumerable<LogRecord>);
        }

        // GET: LogRecords/Details/5

BachelorProject/Views/LogRecords/Delete.cshtml
@*@model BachelorProject.Models.LogRecord

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LogRecord</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfRecord)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfRecord)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Action)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Action)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InfoMessage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InfoMessage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>*@

BachelorProject/Views/LogRecords/Index.cshtml
@*upcast IPagedList*@
@model IEnumerable<BachelorProject.Models.LogRecord>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Oversikt";
}

<h2>Oversikt over de registrerte transaksjonene </h2>
<br />
<div class="container">
    <br />  
    <div class="form-group has-feedback has-search">
        <span class="glyphicon glyphicon-search form-control-feedback"></span>
        @Html.TextBox("searchParameter", "", new { @id = "search", @class = "form-control", @autofocus = "autofocus", @placeholder = "Søk" })

    </div>
    <br />
    <div id="tableDiv" class="table-responsive">
        @if (Model.Count() <= 0)
        {
            <div class="text-center">
                <br />
                <p> Ingen data... </p>
            </div>
        }
        else
        {
            <table class="table table-striped table-responsive-md btn-table w-auto">
                <tr>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Fornavn", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.ApplicationUser.FirstName),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Etternavn", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.ApplicationUser.LastName),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("E-post", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.ApplicationUser.Email),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Dato", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.DateOfRecord),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Hendelse", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.Action),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Informasjon", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.InfoMessage),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            <span>Valg</span>
                        </div>
                    </th>
                </tr>

                @foreach (var item in Model)
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfRecord)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Action)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InfoMessage)
                </td>
                <td>
                    @using (Html.BeginForm("Delete", "LogRecords", new { id = item.Id }, FormMethod.Post,new { }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-actions">
                            <input type="submit" value="Slett" class="btn btn-sm btn-danger" />
                        </div>
                    }
                </td>
            </tr>
                }
            </table>
            <br />


            var pagedList = Model as PagedList.IPagedList<BachelorProject.Models.LogRecord>;

            <p>Side  @(pagedList.PageCount < pagedList.PageNumber ? 0 : pagedList.PageNumber) av @pagedList.PageCount </p>

            @Html.PagedListPager(pagedList,
                         page => Url.Action("UpdateIndex", "LogRecords",
                         new
                         {
                             page
                         }),
                         PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                            new AjaxOptions()
                            {
                                HttpMethod = "GET",
                                UpdateTargetId = "tableDiv"
                            }))
        }

    </div>
</div>




<script>
    $(function () {
        $("#search").keyup(function () {
            $.ajax({
                type: "GET",
                url: "/LogRecords/UpdateIndex",
                data:
                {
                    searchParameter: $("#search").val()
                },
                success: function (data) {
                    $('#tableDiv').html(data);
                }
            });
        });
    });
</script>

BachelorProject/Views/LogRecords/IndexByUserId.cshtml
@*upcast IPagedList*@
@model IEnumerable<BachelorProject.Models.LogRecord>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Oversikt";
}
<h2>Oversikt over ditt forbruk</h2>
<br />
<div class="container">
    <br />
    <div class="form-group has-feedback has-search">
        <span class="glyphicon glyphicon-search form-control-feedback"></span>
        @Html.TextBox("searchParameter", "", new { @id = "search", @class = "form-control", @autofocus = "autofocus", @placeholder = "Søk" })

    </div>
    <br />
    <div id="tableDiv" class="table-responsive">
        @if (Model.Count() <= 0)
        {
            <div class="text-center">
                <br />
                <p> Ingen data... </p>
            </div>
        }
        else
        {
            <table class="table table-striped table-responsive-md btn-table w-auto">
                <tr>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Dato", "UpdateIndexByUserId",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.DateOfRecord),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Hendelse", "UpdateIndexByUserId",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.Action),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Informasjon", "UpdateIndexByUserId",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.InfoMessage),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                </tr>

                @foreach (var item in Model)
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfRecord)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Action)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InfoMessage)
                </td>
            </tr>
                }
            </table>
            <br />


            var pagedList = Model as PagedList.IPagedList<BachelorProject.Models.LogRecord>;

            <p>Side  @(pagedList.PageCount < pagedList.PageNumber ? 0 : pagedList.PageNumber) av @pagedList.PageCount </p>

            @Html.PagedListPager(pagedList,
                         page => Url.Action("UpdateIndexByUserId", "LogRecords",
                         new
                         {
                             page
                         }),
                         PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                            new AjaxOptions()
                            {
                                HttpMethod = "GET",
                                UpdateTargetId = "tableDiv"
                            }))
        }

    </div>
</div>




<script>
    $(function () {
        $("#search").keyup(function () {
            $.ajax({
                type: "GET",
                url: "/LogRecords/UpdateIndexByUserId",
                data:
                {
                    searchParameter: $("#search").val()
                },
                success: function (data) {
                    $('#tableDiv').html(data);
                }
            });
        });
    });
</script>

BachelorProject/Views/LogRecords/UpdateIndex.cshtml
@*upcast IPagedList*@
@model IEnumerable<BachelorProject.Models.LogRecord>
@using PagedList.Mvc;


@if (Model.Count() <= 0)
{
    <div class="text-center">
        <br />
        <p> Ingen data... </p>
    </div>
}
else
{
<table class="table table-striped table-responsive-md btn-table w-auto">
    <tr>
        <th>
            <div class="table_cell">
                @Ajax.ActionLink("Fornavn", "UpdateIndex",
             new
             {
                 sortColumn = Html.DisplayNameFor(model => model.ApplicationUser.FirstName),
                 sortOrder = ViewBag.newSortOrderForFirstName ?? "ASC",
                 searchParameter = ViewBag.searchParameter
             },
             new AjaxOptions
             {
                 HttpMethod = "GET",
                 UpdateTargetId = "tableDiv"
             })
                <i class="fa fa-fw fa-sort"></i>
                </div>
        </th>
        <th>
            <div class="table_cell">
                @Ajax.ActionLink("Etternavn", "UpdateIndex",
             new
             {
                 sortColumn = Html.DisplayNameFor(model => model.ApplicationUser.LastName),
                 sortOrder = ViewBag.newSortOrderForLastName ?? "ASC",
                 searchParameter = ViewBag.searchParameter
             },
             new AjaxOptions
             {
                 HttpMethod = "GET",
                 UpdateTargetId = "tableDiv"
             })
                <i class="fa fa-fw fa-sort"></i>
            </div>
        </th>
        <th>
            <div class="table_cell">
                @Ajax.ActionLink("E-post", "UpdateIndex",
             new
             {
                 sortColumn = Html.DisplayNameFor(model => model.ApplicationUser.Email),
                 sortOrder = ViewBag.newSortOrderForEmail ?? "ASC",
                 searchParameter = ViewBag.searchParameter
             },
             new AjaxOptions
             {
                 HttpMethod = "GET",
                 UpdateTargetId = "tableDiv"
             })
                <i class="fa fa-fw fa-sort"></i>
            </div>
        </th>
        <th>
            <div class="table_cell">
                @Ajax.ActionLink("Dato", "UpdateIndex",
             new
             {
                 sortColumn = Html.DisplayNameFor(model => model.DateOfRecord),
                 sortOrder = ViewBag.newSortOrderForDateOfRecord ?? "ASC",
                 searchParameter = ViewBag.searchParameter
             },
             new AjaxOptions
             {
                 HttpMethod = "GET",
                 UpdateTargetId = "tableDiv"
             })
                <i class="fa fa-fw fa-sort"></i>
            </div>
        </th>
        <th>
            <div class="table_cell">
                @Ajax.ActionLink("Hendelse", "UpdateIndex",
             new
             {
                 sortColumn = Html.DisplayNameFor(model => model.Action),
                 sortOrder = ViewBag.newSortOrderForAction ?? "ASC",
                 searchParameter = ViewBag.searchParameter
             },
             new AjaxOptions
             {
                 HttpMethod = "GET",
                 UpdateTargetId = "tableDiv"
             })
                <i class="fa fa-fw fa-sort"></i>
             </div>
        </th>
        <th>
            <div class="table_cell">
                @Ajax.ActionLink("Informasjon", "UpdateIndex",
             new
             {
                 sortColumn = Html.DisplayNameFor(model => model.InfoMessage),
                 sortOrder = ViewBag.newSortOrderForInfoMessage ?? "ASC",
                 searchParameter = ViewBag.searchParameter
             },
             new AjaxOptions
             {
                 HttpMethod = "GET",
                 UpdateTargetId = "tableDiv"
             })
                <i class="fa fa-fw fa-sort"></i>
             </div>
        </th>
        <th>
            <div class="table_cell">
                <span>Valg</span>
            </div>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfRecord)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Action)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InfoMessage)
            </td>
            <td>
                @using (Html.BeginForm("Delete", "LogRecords", new { id = item.Id }, FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-actions">
                        <input type="submit" value="Slett" class="btn btn-sm btn-danger" />
                    </div>
                }
            </td>
        </tr>
    }
</table>
<br />


    var pagedList = Model as PagedList.IPagedList<BachelorProject.Models.LogRecord>;

<p>Side  @(pagedList.PageCount < pagedList.PageNumber ? 0 : pagedList.PageNumber) av @pagedList.PageCount</p>


@Html.PagedListPager(pagedList,
                             page => Url.Action("UpdateIndex", "LogRecords",
                             new
                             {
                                 page,
                                 searchParameter = ViewBag.searchParameter,
                                 sortColumn = ViewBag.sortColumn,
                                 sortOrder = ViewBag.sortOrder
                             }),
                             PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                                new AjaxOptions()
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                }))
    }