BachelorProject/Models/UserViewModel.cs
using BachelorProject.CustomAttributes;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace BachelorProject.Models
{
    public class UserViewModel
    {
        public static async Task<UserViewModel> CreateAsync(ApplicationUser user, RoleManager<IdentityRole> roleManager)
        {
            var userRoleId = user.Roles.FirstOrDefault().RoleId;
            var createdUserViewModel = new UserViewModel
            {
                UserId = user.Id,
                RoleId = userRoleId,
                Email = user.Email,
                Phone = user.PhoneNumber,
                FirstName = user.FirstName,
                LastName = user.LastName,
                DateOfRecord = user.DateOfRecord,
                Role = (await roleManager.FindByIdAsync(userRoleId)).Name
            };

            return createdUserViewModel;
        }

        public static UserViewModel Create(ApplicationUser user, RoleManager<IdentityRole> roleManager)
        {
            var userRoleId = user.Roles.FirstOrDefault().RoleId;
            var createdUserViewModel = new UserViewModel
            {
                UserId = user.Id,
                RoleId = userRoleId,
                Email = user.Email,
                Phone = user.PhoneNumber,
                FirstName = user.FirstName,
                LastName = user.LastName,
                DateOfRecord = user.DateOfRecord,
                Role = roleManager.FindById(userRoleId).Name
            };

            return createdUserViewModel;
        }

        public static async Task<List<UserViewModel>> CreateFromQueryAsListAsync(IEnumerable<ApplicationUser> userList, RoleManager<IdentityRole> roleManager)
        {
            var viewModelList = new List<UserViewModel>();
            foreach (var user in userList)
            {
                viewModelList.Add(await CreateAsync(user, roleManager));
            }

            return viewModelList;
        }

        public string UserId { get; set; }
        public string RoleId { get; set; }

        [Required]
        [Name(ErrorMessage = "Fornavnet kan inneholde kun bokstaver")]
        public string FirstName { get; set; }

        [Required]
        [Name(ErrorMessage = "Etternavnet kan inneholde kun bokstaver")]
        public string LastName { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "E-post har ugyldig format")]
        public string Email { get; set; }

        [Required]
        [NorwegianPhoneNumber(ErrorMessage = "Telefon har ugyldig format")]
        [Display(Name = "Telefon")]
        public string Phone { get; set; }
        public string Role { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime DateOfRecord { get; set; }

    }
}

BachelorProject/Controllers/UsersController.cs
using BachelorProject.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList; //pagination: ToPagedList()
using PagedList.EntityFramework; // pagination async: ToPagedListAsync()

namespace BachelorProject.Controllers
{
    [Authorize(Roles = "admin")]
    public class UsersController : Controller
    {
        private ApplicationDbContext db;
        private UserStore<ApplicationUser> us;
        private ApplicationUserManager userManager;
        //public static just in order to make it accessible???
        private RoleManager<IdentityRole> roleManager;

        public UsersController()
        {
            db = new ApplicationDbContext();
            us = new UserStore<ApplicationUser>(db);
            userManager = new ApplicationUserManager(us);
            roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
        }

        // GET: Users
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Index()
        {
            ViewBag.searchParameter = "";

            int pageSize = 10;
            int pageNumber = 1;

            //cannot do it like this due to EF6 sql statements mixing with C# code.
            //linq queries cannot recognize inner c# statements as they are being converted to sql statements
            //var users = userManager.Users.Select(user => UserViewModel.Create(user, roleManager));

            //.ToList() closes the SqlReader !! If not closed then must edit config to allow multiple readers to access the sql table
            //get admin role id
            string adminRoleId = (await roleManager.FindByNameAsync("admin")).Id;
            //exclude admin from the result
            var users = await userManager.Users.Where(user =>user.Roles.FirstOrDefault().RoleId != adminRoleId).ToListAsync();
            var viewModelList = await UserViewModel.CreateFromQueryAsListAsync(users, roleManager);

            return View(viewModelList.OrderBy(record => record.UserId).ToPagedList(pageNumber, pageSize));
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> UpdateIndex(string searchParameter, int? page, string sortColumn, string sortOrder)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;

            IEnumerable<UserViewModel> viewModelList;
            IEnumerable<ApplicationUser> users;

            //filtering the query
            if (searchParameter != null && searchParameter != "")
            {
                //searching through the email, first name and last name
                ViewBag.searchParameter = searchParameter;
                //get admin role id
                string adminRoleId = (await roleManager.FindByNameAsync("admin")).Id;
                //exclude admin from the result
                users = db.Users.Where(user => user.Roles.FirstOrDefault().RoleId != adminRoleId)
                                .Where(d => d.Email.Contains(searchParameter) || d.FirstName.Contains(searchParameter) || d.LastName.Contains(searchParameter))
                                .ToList();
            }
            else
            {
                //searchParameter is null, i.e. no filter is specified
                //get admin role id
                string adminRoleId = (await roleManager.FindByNameAsync("admin")).Id;
                //exclude admin from the result
                users = db.Users.Where(user => user.Roles.FirstOrDefault().RoleId != adminRoleId).ToList();
            }

            viewModelList = await UserViewModel.CreateFromQueryAsListAsync(users, roleManager);

            //sorting the query
            ViewBag.sortColumn = sortColumn; //this can be null
            ViewBag.sortOrder = sortOrder; //this can be null
            switch (sortColumn)
            {
                case "FirstName":
                    if (sortOrder == "ASC")
                    {
                        viewModelList = viewModelList.OrderBy(d => d.FirstName);
                        ViewBag.newSortOrderForFirstName = "DESC";
                    }
                    else
                    {
                        viewModelList = viewModelList.OrderByDescending(d => d.FirstName);
                        ViewBag.newSortOrderForFirstName = "ASC";
                    }
                    break;
                case "LastName":
                    if (sortOrder == "ASC")
                    {
                        viewModelList = viewModelList.OrderBy(d => d.LastName);
                        ViewBag.newSortOrderForLastName = "DESC";
                    }
                    else
                    {
                        viewModelList = viewModelList.OrderByDescending(d => d.LastName);
                        ViewBag.newSortOrderForLastName = "ASC";
                    }
                    break;
                case "Email":
                    if (sortOrder == "ASC")
                    {
                        viewModelList = viewModelList.OrderBy(d => d.Email);
                        ViewBag.newSortOrderForEmail = "DESC";
                    }
                    else
                    {
                        viewModelList = viewModelList.OrderByDescending(d => d.Email);
                        ViewBag.newSortOrderForEmail = "ASC";
                    }
                    break;
                case "Telefon":
                    if (sortOrder == "ASC")
                    {
                        viewModelList = viewModelList.OrderBy(d => d.Phone);
                        ViewBag.newSortOrderForPhone = "DESC";
                    }
                    else
                    {
                        viewModelList = viewModelList.OrderByDescending(d => d.Phone);
                        ViewBag.newSortOrderForPhone = "ASC";
                    }
                    break;
                case "Role":
                    if (sortOrder == "ASC")
                    {
                        viewModelList = viewModelList.OrderBy(d => d.Role);
                        ViewBag.newSortOrderForRole = "DESC";
                    }
                    else
                    {
                        viewModelList = viewModelList.OrderByDescending(d => d.Role);
                        ViewBag.newSortOrderForRole = "ASC";
                    }
                    break;
                case "DateOfRecord":
                    if (sortOrder == "ASC")
                    {
                        viewModelList = viewModelList.OrderBy(d => d.DateOfRecord);
                        ViewBag.newSortOrderForRole = "DESC";
                    }
                    else
                    {
                        viewModelList = viewModelList.OrderByDescending(d => d.DateOfRecord);
                        ViewBag.newSortOrderForRole = "ASC";
                    }
                    break;
                default:
                    viewModelList = viewModelList.OrderBy(s => s.UserId);
                    break;
            }


            var viewResult = viewModelList.ToPagedList(pageNumber, pageSize);
            return PartialView("UpdateIndex", viewResult as IEnumerable<UserViewModel>);
        }

        // GET: Users/Details/5
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            UserViewModel userViewModel = await UserViewModel.CreateAsync(user, roleManager);
            return View(userViewModel); 
        }

        // GET: Users/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            UserViewModel model = await UserViewModel.CreateAsync(user, roleManager);
            ViewBag.dropdownlist = new SelectList(db.Roles.Where(role=>role.Name!="admin").OrderBy(role => role.Name), "Id", "Name", model.RoleId);
            return View(model);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "UserId,RoleId,FirstName,LastName,Email,Phone,DateOfRecord")] UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                //Do not have all info about user to create a complede user model
                ApplicationUser user = userManager.FindById(userViewModel.UserId);
                user.FirstName = userViewModel.FirstName;
                user.LastName = userViewModel.LastName;
                user.Email = userViewModel.Email;
                user.PhoneNumber = userViewModel.Phone;
                user.UserName = userViewModel.Email;

                ////editing user role
                //removing user from all roles
                var roles = await userManager.GetRolesAsync(user.Id);
                await userManager.RemoveFromRolesAsync(user.Id, roles.ToArray());
                await db.SaveChangesAsync();

BachelorProject/Views/Users/Delete.cshtml
@model BachelorProject.Models.UserViewModel

@{
    ViewBag.Title = "Slett";
}
<div class="container" style="word-break: break-word">
        <h2>Er du sikker på at du vil slette brukeren?</h2>
        <hr />

        <dl class="dl-horizontal form-horizontal">
            <div class="form-group">
                <dt>
                    <span>Fornavn</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FirstName)
                </dd>
            </div>

            <div class="form-group">
                <dt>
                    <span>Etternavn</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LastName)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>E-post</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Telefon</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Phone)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Rolle</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Role)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Registreringsdato</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateOfRecord)
                </dd>
            </div>
            <div class="form-group">
                <dd>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions">
                            <input type="submit" value="Slett" class="btn btn-danger" />
                        </div>
                    }
                </dd>
            </div>
        </dl>
</div>
<div>
    <button type="button" class="btn btn-primary m-0" onclick="location.href='@Url.Action("Index","Users")'">Tilbake til oversikten</button>
</div>

BachelorProject/Views/Users/Details.cshtml
@model BachelorProject.Models.UserViewModel

@{
    ViewBag.Title = "Detaljer";
}


<div class="container" style="word-break: break-word">
    <form>
        <h2>Informasjon om brukeren</h2>
        <hr />

        <dl class="dl-horizontal form-horizontal">
            <div class="form-group">
                <dt>
                    <span>Fornavn</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FirstName)
                </dd>
            </div>

            <div class="form-group">
                <dt>
                    <span>Etternavn</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LastName)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>E-post</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Telefon</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Phone)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Rolle</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Role)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Registreringsdato</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateOfRecord)
                </dd>
            </div>
            <div class="form-group">
                <dd><button type="button" class="btn btn-success m-0" onclick="location.href='@Url.Action("Edit","Users",new { id = Model.UserId })'">Rediger</button></dd>
            </div>
        </dl>
    </form>

</div>

<div>
    <button type="button" class="btn btn-primary m-0" onclick="location.href='@Url.Action("Index","Users")'">Tilbake til oversikten</button>
</div>

BachelorProject/Views/Users/Edit.cshtml
@model BachelorProject.Models.UserViewModel

@{
    ViewBag.Title = "Rediger";
}
<h2>Rediger</h2>


@if (ViewBag.ErrorMessage != null)
{
    <p class="text-danger"> Feilmelding: @Html.Raw(ViewBag.ErrorMessage) </p>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.UserId)

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, "Fornavn", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, "Etternavn", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, "E-post", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Phone, "Telefon", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RoleId, "Rolle", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.RoleId, ViewBag.dropdownlist as SelectList, new { @id = "dropdownlist", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lagre" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    <button type="button" class="btn btn-primary m-0" onclick="location.href='@Url.Action("Index","Users")'">Tilbake til oversikten</button>
</div>



@*this section must be here in order to enable client side validation*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BachelorProject/Views/Users/Index.cshtml
@*upcast IPagedList*@
@model IEnumerable<BachelorProject.Models.UserViewModel>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Oversikt";
}
<h2>Oversikt over brukere</h2>
<br />
<div class="container">
    <br />
    <div class="form-group has-feedback has-search">
        <span class="glyphicon glyphicon-search form-control-feedback"></span>
        @Html.TextBox("searchParameter", "", new { @id = "search", @class = "form-control", @autofocus = "autofocus", @placeholder = "Søk" })

    </div>
    <br />
    <div id="tableDiv" class="table-responsive">
        @if (Model.Count() <= 0)
        {
            <div class="text-center">
                <br />
                <p> Ingen data... </p>
            </div>
        }
        else
        {
            <table class="table table-striped table-responsive-md btn-table w-auto">
                <tr>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Fornavn", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.FirstName),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Etternavn", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.LastName),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("E-post", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.Email),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Telefon", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.Phone),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Rolle", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.Role),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Registreringsdato", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.DateOfRecord),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            Valg
                        </div>
                    </th>
                </tr>

                @foreach (var item in Model)
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Role)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfRecord)
                </td>
                <td>
                    <button type="button" class="btn btn-primary btn-sm m-0" onclick="location.href='@Url.Action("Edit","Users",new { id = item.UserId })'">Rediger</button>
                    <button type="button" class="btn btn-info btn-sm m-0" onclick="location.href='@Url.Action("Details","Users",new { id = item.UserId })'">Detaljer</button>
                    <button type="button" class="btn btn-danger btn-sm m-0" onclick="location.href='@Url.Action("Delete","Users",new { id = item.UserId })'">Slett</button>
                </td>
            </tr>
                }
            </table>
            <br />


            var pagedList = Model as PagedList.IPagedList<BachelorProject.Models.UserViewModel>;

            <p>Side  @(pagedList.PageCount < pagedList.PageNumber ? 0 : pagedList.PageNumber) av @pagedList.PageCount </p>

            @Html.PagedListPager(pagedList,
                         page => Url.Action("UpdateIndex", "Users",
                         new
                         {
                             page
                         }),
                         PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                            new AjaxOptions()
                            {
                                HttpMethod = "GET",
                                UpdateTargetId = "tableDiv"
                            }))
        }

    </div>
</div>


<script>
    $(function () {
        $("#search").keyup(function () {
            $.ajax({
                type: "GET",
                url: "/Users/UpdateIndex",
                data:
                {
                    searchParameter: $("#search").val()
                },
                success: function (data) {
                    $('#tableDiv').html(data);
                }
            });
        });
    });
</script>