BachelorProject/Models/DepotRecord.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using BachelorProject.CustomAttributes;
using BachelorProject.Properties;

namespace BachelorProject.Models
{
    public class DepotRecord
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [ForeignKey("Equipment")]
        public int EquipmentCodeId { get; set; }
        public Equipment Equipment { get; set; }

        
        [DataType(DataType.Date, ErrorMessageResourceName = "DateErrror", ErrorMessageResourceType = typeof(ValidationResources))]
        //DataFormatString must be ISO standard {0:yyyy-MM-dd}, see https://stackoverflow.com/questions/31097748/date-does-not-display-from-model-on-html-input-type-date
        //otherwise value="{date}" will not work in VIEW
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ConvertEmptyStringToNull =true,NullDisplayText = "Ingen utløpsdato", ApplyFormatInEditMode = true)]
        public DateTime? ExpirationDate { get; set; } //using nullable type because the field can be null

        [DataType(DataType.Date)]
        //this attribute defined display format in input fields:
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ConvertEmptyStringToNull = true, NullDisplayText = "Ingen utløpsdato", ApplyFormatInEditMode = true)]
        public DateTime DateOfRecord { get; set; }
        
        [Required(ErrorMessage = "Feltet Antall er obligatorisk!")]
        [NotNegativeNumber(ErrorMessage = "Verdien må være større enn 0")]
        public int QuantityOriginal { get; set; }
        [Required]
        public int QuantityLeft { get; set; }

        public string Information { get; set; } //can be used to write comments

        //not necessary yet:
        //FK
        //public int DistributorId { get; set; }

        //public Distributor Distributor { get; set; }

        //not necessary yet:
        //FK
        //public int IsAtLocationId { get; set; }

        //public Location Location { get; set; }
    }
}

BachelorProject/Models/DepotRecordViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BachelorProject.Models
{
    //public class DepotRecordViewModel
    //{
    //public int CoideId { get; set; }
    //    public DateTime ExpirationDate { get; set; }
    //    public int QuantityOriginal { get; set; }
    //    public int QuantityLeft { get; set; }
    //    public string Name { get; set; }
    //    public string Type { get; set; }
    //}
}

BachelorProject/Controllers/DepotRecordsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BachelorProject.Models;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity.EntityFramework;
using System.IO;
using System.Net.Mail;
using System.Collections.Specialized;
using System.Web.Routing;
using PagedList; //pagination
using PagedList.EntityFramework; // pagination async: ToPagedListAsync()
using Microsoft.AspNet.Identity;
using System.Globalization;

namespace BachelorProject.Controllers
{
    [Authorize]
    public class DepotRecordsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserStore<ApplicationUser> us;
        private readonly ApplicationUserManager userManager;
        public DepotRecordsController()
        {
            db = new ApplicationDbContext();
            us = new UserStore<ApplicationUser>(db);
            userManager = new ApplicationUserManager(us);
        }


        //protected override void Initialize(RequestContext requestContext)
        //{
        //    base.Initialize(requestContext);
        //    string cultureInfo = "nb-NO";
        //    System.Threading.Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo(cultureInfo);
        //    System.Threading.Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(cultureInfo);
        //    base.Initialize(requestContext);
        //}

        //NB!!
        //Can create a view model and use it --> much more convenient

        // GET: DepotRecords

        [Authorize(Roles = "admin,subAdmin")]
        public async Task<ActionResult> Index()
        {   
            var depotRecords = db.DepotRecords.Include(d => d.Equipment);

            ViewBag.searchParameter = "";

            int pageSize = 10;
            int pageNumber = 1;
            return View(await depotRecords.OrderBy(record => record.Id).ToPagedListAsync(pageNumber,pageSize));
        }

        [Authorize(Roles = "admin,subAdmin")]
        public async Task<ActionResult> UpdateIndex(string searchParameter, int? page, string sortColumn, string sortOrder)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;

            //Either access parameter like this:
            //var par = Request.QueryString["searchParameter"];
            //Or like this:
            //string par;

            //anonymous object could be passed as json:
            //var result = from e in db.DepotRecords
            //             where e.Equipment.NameAndType.Contains(par)
            //             select new
            //             {
            //                 e.Equipment.NameAndType,
            //                 e.ExpirationDate,
            //                 e.QuantityOriginal,
            //                 e.QuantityLeft
            //             };

            var result = db.DepotRecords.Include(d => d.Equipment);

            //filtering the query
            if (searchParameter != null && searchParameter != "")
            {
                ViewBag.searchParameter = searchParameter;
                result = result.Where(d => d.Equipment.NameAndType.Contains(searchParameter));
            }

            //sorting the query
            ViewBag.sortColumn = sortColumn; //this can be null
            ViewBag.sortOrder = sortOrder; //this can be null
            switch (sortColumn)
            {
                case "Id":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.Id);
                        ViewBag.newSortOrderForId = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.Id);
                        ViewBag.newSortOrderForId = "ASC";
                    }
                    break;
                case "NameAndType":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.Equipment.NameAndType);
                        ViewBag.newSortOrderForNameAndType = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.Equipment.NameAndType);
                        ViewBag.newSortOrderForNameAndType = "ASC";
                    }
                    break;
                case "DateOfRecord":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.DateOfRecord);
                        ViewBag.newSortOrderForDateOfRecord = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.DateOfRecord);
                        ViewBag.newSortOrderForDateOfRecord = "ASC";
                    }
                    break;
                case "ExpirationDate":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.ExpirationDate);
                        ViewBag.newSortOrderForExpirationDate = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.ExpirationDate);
                        ViewBag.newSortOrderForExpirationDate = "ASC";
                    }
                    break;
                case "QuantityOriginal":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.QuantityOriginal);
                        ViewBag.newSortOrderForQuantityOriginal = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.QuantityOriginal);
                        ViewBag.newSortOrderForQuantityOriginal = "ASC";
                    }
                    break;
                case "QuantityLeft":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.QuantityLeft);
                        ViewBag.newSortOrderForQuantityLeft = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.QuantityLeft);
                        ViewBag.newSortOrderForQuantityLeft = "ASC";
                    }
                    break;
                default:
                    result = result.OrderBy(s => s.Id);
                    break;
            }


            var viewResult = await result.ToPagedListAsync(pageNumber, pageSize);
            return PartialView("UpdateIndex", viewResult as IEnumerable<DepotRecord>);
        }

        // GET: DepotRecords/Details/5
        [Authorize(Roles = "admin,subAdmin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var depotRecord = (await db.DepotRecords.Include(d => d.Equipment).ToListAsync())
                              .Find(record => record.Id == id);
            if (depotRecord == null)
            {
                return HttpNotFound();
            }
            return View(depotRecord);
        }

        // GET: DepotRecords/Create
        [Authorize(Roles = "admin,subAdmin")]
        public ActionResult Create()
        {
            ViewBag.selectList = new SelectList(db.Equipments.OrderBy(r => r.NameAndType), "Id", "NameAndType");
            return View();
        }

        // POST: DepotRecords/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin,subAdmin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "EquipmentCodeId,ExpirationDate,QuantityOriginal,Information")] DepotRecord depotRecord)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    depotRecord.QuantityLeft = depotRecord.QuantityOriginal;
                    depotRecord.DateOfRecord = DateTime.Now;
                    depotRecord = db.DepotRecords.Add(depotRecord);
                    await db.SaveChangesAsync();
                    var controller = DependencyResolver.Current.GetService<LogRecordsController>();
                    controller.ControllerContext = new ControllerContext(this.Request.RequestContext, controller);
                    controller.Create(
                        new LogRecord
                        {
                            UserId = this.User.Identity.GetUserId(),
                            DateOfRecord = DateTime.Now,
                            Action = LogAction.NYTT_UTSTYR,
                            InfoMessage = string.Format(
                                                        "NYTT UTSTYR. Utstyr-ID: {0}; Type-ID: {1}; Utløpsdato: {2}; Antall opprinnelig: {3}",
                                                        depotRecord.Id,
                                                        depotRecord.EquipmentCodeId,
                                                        (depotRecord.ExpirationDate != null) ? depotRecord.ExpirationDate.Value.ToShortDateString() : "Ingen",
                                                        depotRecord.QuantityOriginal
                                                        )
                        });
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {

BachelorProject/Views/DepotRecords/Create.cshtml
@model BachelorProject.Models.DepotRecord

@{
    ViewBag.Title = "Lag ny";
}


@using (Html.BeginForm("Create", "DepotRecords", FormMethod.Post, htmlAttributes: new { @id = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Legg til et utstyr på lageret</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EquipmentCodeId, "Navn og type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EquipmentCodeId, ViewBag.selectList as SelectList, new { @id = "dropdownlist", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EquipmentCodeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Har utstyret utløpsdato?", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="radio_yes" type="radio" name="expiration" value="YES" checked>
                <label for="radio_yes">Ja</label>
                <input id="radio_no" type="radio" name="expiration" value="NO">
                <label for="radio_no">Nei</label>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, "Utløpsdato", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control", @id = "exp_date" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
                @*<span class="help-block">La feltet være blankt hvis utsyr ikke har utløpsdato!</span>*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityOriginal, "Antall", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantityOriginal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantityOriginal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Information, "Kommentar", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Information, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Information, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send inn" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-primary m-0" onclick="location.href='@Url.Action("Index","DepotRecords")'">Tilbake til oversikten</button>
</div>

<script>
    $(function () {
        $('input[type = "radio"]').change(function () {
            if ($(this).val() == 'YES') {
                $("#exp_date").prop('disabled', false);
            } else {
                $("#exp_date").prop('disabled', true);
                $("#exp_date").val("");
            }
        });
    });

    $(document).ready(function () {
        $('#form').on('submit', function (e) {
            e.preventDefault();
            var dateRegex = /^\d{4}-\d{2}-\d{2}$/;
            var checked = $('input[name="expiration"]:checked').val();
            if (checked == "NO") {
                this.submit();
            }
            else if ($('#exp_date').val().match(dateRegex) && checked == "YES") {
                this.submit();
            }
            else {
                alert("Skriv inn riktig utløpsdato!");
            }

        });
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BachelorProject/Views/DepotRecords/Delete.cshtml
@model BachelorProject.Models.DepotRecord

@{
    ViewBag.Title = "Slett";
}

<div class="container" style="word-break: break-word">
    
        <h2>Er du sikker på at du vil slette dette?</h2>
        <hr />

        <dl class="dl-horizontal form-horizontal">
            <div class="form-group">
                <dt>
                    <span>ID</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Id)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Navn og type</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Equipment.NameAndType)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Opprettingsdato</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateOfRecord)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Utløpsdato</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ExpirationDate)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Antall opprinnelig</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.QuantityOriginal)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Antall igjen</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.QuantityLeft)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Kommentar</span>
                </dt>

                <dd style="width: 40%">
                    @Html.DisplayFor(model => model.Information)
                </dd>
            </div>
            <div class="form-group">
                <dd>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions">
                            <input type="submit" value="Slett" class="btn btn-danger" />
                        </div>
                    }
                </dd>
            </div>
        </dl>
    
</div>
<div>
    <button type="button" class="btn btn-primary m-0" onclick="location.href='@Url.Action("Index","DepotRecords")'">Tilbake til oversikten</button>
</div>

BachelorProject/Views/DepotRecords/Details.cshtml
@model BachelorProject.Models.DepotRecord

@{
    ViewBag.Title = "Detaljer";
}

<div class="container" style="word-break: break-word">
    <form>
        <h2>Informasjon om utstyret</h2>
        <hr />
        
        <dl class="dl-horizontal form-horizontal">
            <div class="form-group">
                <dt>
                    <span>ID</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Id)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Navn og type</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Equipment.NameAndType)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Opprettingsdato</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateOfRecord)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Utløpsdato</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ExpirationDate)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    @*@Html.DisplayNameFor(model => model.QuantityOriginal)*@
                    <span>Antall opprinnelig</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.QuantityOriginal)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Antall igjen</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.QuantityLeft)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Kommentar</span>
                </dt>

                <dd style="width: 40%">
                    @Html.DisplayFor(model => model.Information)
                </dd>
            </div>
            <div class="form-group">
                <dd><button type="button" class="btn btn-success m-0" onclick="location.href='@Url.Action("Edit","DepotRecords",new { id = Model.Id })'">Rediger</button></dd>
            </div>
        </dl>
    </form>
    
</div>

<div>
    <button type="button" class="btn btn-primary m-0" onclick="location.href='@Url.Action("Index","DepotRecords")'">Tilbake til oversikten</button>
</div>
    
    

BachelorProject/Views/DepotRecords/Edit.cshtml
@model BachelorProject.Models.DepotRecord

@{
    ViewBag.Title = "Rediger";
}

<h2>Rediger info</h2>


@if (ViewBag.ErrorMessage != null)
{
    <p class="text-danger"> Feilmelding: @Html.Raw(ViewBag.ErrorMessage) </p>
}
@using (Html.BeginForm("Edit", "DepotRecords", FormMethod.Post, htmlAttributes: new { @id = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfRecord, "Opprettingsdato", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfRecord, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.DateOfRecord, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EquipmentCodeId, "Navn og type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EquipmentCodeId, ViewBag.dropDownList as SelectList, new { @id = "dropdownlist", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EquipmentCodeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Har utstyret utløpsdato?", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="radio_yes" type="radio" name="expiration" value="YES" checked>
                <label for="radio_yes">Ja</label>
                <input id="radio_no" type="radio" name="expiration" value="NO">
                <label for="radio_no">Nei</label>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, "Utløpsdato", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control", @id = "exp_date" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityOriginal, "Antall opprinnelig", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantityOriginal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantityOriginal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityLeft, "Antall gjenværende", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantityLeft, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantityLeft, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Information, "Kommentar", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Information, new { @class = "form-control", @rows = "5" })
                @Html.ValidationMessageFor(model => model.Information, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lagre" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-primary m-0" onclick="location.href='@Url.Action("Index","DepotRecords")'">Tilbake til oversikten</button>
</div>

<script>
    $(function () {
        $('input[type = "radio"]').change(function () {
            if ($(this).val() == 'YES') {
                $("#exp_date").prop('disabled', false);
            } else {
                $("#exp_date").prop('disabled', true);
                $("#exp_date").val("");
            }
        });
    });

    $(document).ready(function () {
        $('#form').on('submit', function (e) {
            e.preventDefault();
            var dateRegex = /^\d{4}-\d{2}-\d{2}$/;
            var checked = $('input[name="expiration"]:checked').val();
            if (checked == "NO") {
                this.submit();
            }
            else if ($('#exp_date').val().match(dateRegex) && checked == "YES") {
                this.submit();
            }
            else {
                alert("Skriv inn riktig utløpsdato!");
            }

        });
    });
</script>

@*this section must be here in order to enable client side validation*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BachelorProject/Views/DepotRecords/ReduceQuantity.cshtml
@model BachelorProject.Models.ReduceAmountViewModel
@{
    ViewBag.Title = "Forbruk";
}
<h2>Registrer antall av brukt utstyr</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @if (ViewBag.StatusMessage != null)
    {
        <ul>
            <li class="text-success"> @Html.Raw(ViewBag.StatusMessage) </li>
        </ul>        
    }

    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.EquipmentCodeId, "Navn og type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.EquipmentCodeId, ViewBag.dropDownList as SelectList, new { @id = "dropdownlist", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EquipmentCodeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ReduceQuantity, "Antall", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ReduceQuantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ReduceQuantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Send inn" class="btn btn-success" />
        </div>
    </div>
</div>
}


@*this section makes sure that jqueryval packages for jquery client side validation are included*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BachelorProject/Views/DepotRecords/SearchResult.cshtml
@model IEnumerable<BachelorProject.Models.DepotRecord>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Equipment.NameAndType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuantityOriginal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuantityLeft)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Equipment.NameAndType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpirationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuantityOriginal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuantityLeft)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>