BachelorProject/Models/Equipment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BachelorProject.Models
{
    public class Equipment
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Column(TypeName = "VARCHAR")]
        [StringLength(300)]
        [Index("IX_NameAndType", 1, IsUnique = true)]
        [Required(ErrorMessage = "Feltet 'Navn og Type' er obligatorisk")]
        public string NameAndType { get; set; }
        public ICollection<DepotRecord> DepotRecord { get; set; }

        ////Can be applied later:
        //[Column(TypeName = "VARCHAR")]
        //[StringLength(300)]
        //[Index("IX_NameAndType", 2, IsUnique = true)]
        //public string Type { get; set; }
    }
}

BachelorProject/Controllers/EquipmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BachelorProject.Models;
using PagedList; //pagination: ToPagedList()
using PagedList.EntityFramework; // pagination async: ToPagedListAsync()

namespace BachelorProject.Controllers
{
    [Authorize]
    public class EquipmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Equipments
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Index()
        {
            var equipment = db.Equipments;

            ViewBag.searchParameter = "";
            int pageSize = 10;
            int pageNumber = 1;
            return View(await equipment.OrderBy(record => record.Id).ToPagedListAsync(pageNumber, pageSize));
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> UpdateIndex(string searchParameter, int? page, string sortColumn, string sortOrder)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;

            IQueryable<Equipment> result;

            //filtering the query
            if (searchParameter != null && searchParameter != "")
            {
                ViewBag.searchParameter = searchParameter;
                result = db.Equipments
                            //filter
                           .Where(d => d.NameAndType.Contains(searchParameter));
            }
            else
            {
                //searchParameter is null, i.e. no filter is specified
                result = db.Equipments;
            }

            //sorting the query
            ViewBag.sortColumn = sortColumn; //this can be null
            ViewBag.sortOrder = sortOrder; //this can be null
            switch (sortColumn)
            {
                case "Id":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.Id);
                        ViewBag.newSortOrderForId = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.Id);
                        ViewBag.newSortOrderForId = "ASC";
                    }
                    break;
                case "NameAndType":
                    if (sortOrder == "ASC")
                    {
                        result = result.OrderBy(d => d.NameAndType);
                        ViewBag.newSortOrderForNameAndType = "DESC";
                    }
                    else
                    {
                        result = result.OrderByDescending(d => d.NameAndType);
                        ViewBag.newSortOrderForNameAndType = "ASC";
                    }
                    break;
                default:
                    result = result.OrderBy(s => s.Id);
                    break;
            }


            var viewResult = await result.ToPagedListAsync(pageNumber, pageSize);
            return PartialView("UpdateIndex", viewResult as IEnumerable<Equipment>);
        }

        // GET: Equipments/Details/5
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipment equipment = await db.Equipments.FindAsync(id);
            if (equipment == null)
            {
                return HttpNotFound();
            }
            return View(equipment);
        }

        // GET: Equipments/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Equipments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,NameAndType")] Equipment equipment)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Equipments.Add(equipment);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", "Noe gikk galt. Vennligst prøv igjen.");
                    ModelState.AddModelError("", "Tips: utstyret kan ikke ha duplisert navn.");
                    return View(equipment);
                }
            }   
            return View(equipment);
        }

        // GET: Equipments/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipment equipment = await db.Equipments.FindAsync(id);
            if (equipment == null)
            {
                return HttpNotFound();
            }
            return View(equipment);
        }

        // POST: Equipments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,NameAndType")] Equipment equipment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(equipment).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(equipment);
        }

        // GET: Equipments/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipment equipment = await db.Equipments.FindAsync(id);
            if (equipment == null)
            {
                return HttpNotFound();
            }
            return View(equipment);
        }

        // POST: Equipments/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                Equipment equipment = await db.Equipments.FindAsync(id);
                db.Equipments.Remove(equipment);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View("Error");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BachelorProject/Views/Equipments/Create.cshtml
@model BachelorProject.Models.Equipment

@{
    ViewBag.Title = "Lag ny";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2>Legg til ny utstyrtype</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NameAndType,"Navn og type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameAndType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameAndType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send inn" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-primary m-0" onclick="location.href='@Url.Action("Index","Equipments")'">Tilbake til oversikten</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BachelorProject/Views/Equipments/Delete.cshtml
@model BachelorProject.Models.Equipment

@{
    ViewBag.Title = "Slett";
}

<div class="container" style="word-break: break-word">

    <h2>Er du sikker på at du vil slette dette?</h2>
    <hr />

    <dl class="dl-horizontal form-horizontal">
        <div class="form-group">
            <dt>
                <span>ID</span>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Id)
            </dd>
        </div>
        <div class="form-group">
            <dt>
                <span>Navn og type</span>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NameAndType)
            </dd>
        </div>

        <div class="form-group">
            <dd>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions">
                        <input type="submit" value="Slett" class="btn btn-danger" />
                    </div>
                }
            </dd>
        </div>
    </dl>

</div>
<div>
    <button type="button" class="btn btn-primary m-0" onclick="location.href='@Url.Action("Index","Equipments")'">Tilbake til oversikten</button>
</div>

BachelorProject/Views/Equipments/Details.cshtml
@model BachelorProject.Models.Equipment

@{
    ViewBag.Title = "Detaljer";
}

<div class="container" style="word-break: break-word">
    <form>
        <h2>Informasjon om utstyret</h2>
        <hr />

        <dl class="dl-horizontal form-horizontal">
            <div class="form-group">
                <dt>
                    <span>ID</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Id)
                </dd>
            </div>
            <div class="form-group">
                <dt>
                    <span>Navn og type</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NameAndType)
                </dd>
            </div>

            <div class="form-group">
                <dd><button type="button" class="btn btn-success m-0" onclick="location.href='@Url.Action("Edit","Equipments",new { id = Model.Id })'">Rediger</button></dd>
            </div>
        </dl>
    </form>

</div>

<div>
    <button type="button" class="btn btn-primary m-0" onclick="location.href='@Url.Action("Index","Equipments")'">Tilbake til oversikten</button>
</div>

BachelorProject/Views/Equipments/Edit.cshtml
@model BachelorProject.Models.Equipment

@{
    ViewBag.Title = "Rediger";
}

<h2>Rediger</h2>

@if (ViewBag.ErrorMessage != null)
{
    <p class="text-danger"> Feilmelding: @Html.Raw(ViewBag.ErrorMessage) </p>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Rediger registrering</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.NameAndType, "Navn og type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameAndType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameAndType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lagre" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-primary m-0" onclick="location.href='@Url.Action("Index","Equipments")'">Tilbake til oversikten</button>
</div>



@*this section must be here in order to enable client side validation*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BachelorProject/Views/Equipments/Index.cshtml
@*upcast IPagedList*@
@model IEnumerable<BachelorProject.Models.Equipment>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Oversikt";
}
<h2>Oversikt over typer utstyr</h2>
<br />
<div class="container">
    <div>
        <p>
            <button type="button" class="btn btn-success m-0" onclick="location.href='@Url.Action("Create","Equipments")'">Legg til et nytt utstyr</button>
        </p>
    </div>
    <br />
    <div class="form-group has-feedback has-search">
        <span class="glyphicon glyphicon-search form-control-feedback"></span>
        @Html.TextBox("searchParameter", "", new { @id = "search", @class = "form-control", @autofocus = "autofocus", @placeholder = "Søk" })

    </div>
    <br />
    <div id="tableDiv" class="table-responsive">
        @if (Model.Count() <= 0)
        {
            <div class="text-center">
                <br />
                <p> Ingen data... </p>
            </div>
        }
        else
        {
            <table class="table table-striped table-responsive-md btn-table w-auto">
                <tr>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("ID", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.Id),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            @Ajax.ActionLink("Navn og Type", "UpdateIndex",
                                new
                                {
                                    sortColumn = Html.DisplayNameFor(model => model.NameAndType),
                                    sortOrder = "ASC"
                                },
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "tableDiv"
                                })
                            <i class="fa fa-fw fa-sort"></i>
                        </div>
                    </th>
                    <th>
                        <div class="table_cell">
                            Valg
                        </div>
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NameAndType)
                        </td>
                        <td>
                            <button type="button" class="btn btn-primary btn-sm m-0" onclick="location.href='@Url.Action("Edit","Equipments",new { id = item.Id })'">Rediger</button>
                            <button type="button" class="btn btn-info btn-sm m-0" onclick="location.href='@Url.Action("Details","Equipments",new { id = item.Id })'">Detaljer</button>
                            <button type="button" class="btn btn-danger btn-sm m-0" onclick="location.href='@Url.Action("Delete","Equipments",new { id = item.Id })'">Slett</button>
                        </td>
                    </tr>
                }
            </table>
            <br />


            var pagedList = Model as PagedList.IPagedList<BachelorProject.Models.Equipment>;

            <p>Side  @(pagedList.PageCount < pagedList.PageNumber ? 0 : pagedList.PageNumber) av @pagedList.PageCount </p>

            @Html.PagedListPager(pagedList,
                         page => Url.Action("UpdateIndex", "Equipments",
                         new
                         {
                             page
                         }),
                         PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                            new AjaxOptions()
                            {
                                HttpMethod = "GET",
                                UpdateTargetId = "tableDiv"
                            }))
        }

    </div>
</div>

<script>
    $(function () {
        $("#search").keyup(function () {
            $.ajax({
                type: "GET",
                url: "/Equipments/UpdateIndex",
                data:
                {
                    searchParameter: $("#search").val()
                },
                success: function (data) {
                    $('#tableDiv').html(data);
                }
            });
        });
    });
</script>

BachelorProject/Views/Equipments/UpdateIndex.cshtml
@*upcast IPagedList*@
@model IEnumerable<BachelorProject.Models.Equipment>
@using PagedList.Mvc;

    @if (Model.Count() <= 0)
    {
        <div class="text-center">
            <br />
            <p> Ingen data... </p>
        </div>
    }
    else
    {
        <table class="table table-striped table-responsive-md btn-table w-auto">
            <tr>
                <th>
                    <div class="table_cell">
                        @Ajax.ActionLink("ID", "UpdateIndex",
                            new
                            {
                                sortColumn = Html.DisplayNameFor(model => model.Id),
                                sortOrder = ViewBag.newSortOrderForId ?? "ASC",
                                searchParameter = ViewBag.searchParameter
                            },
                            new AjaxOptions
                            {
                                HttpMethod = "GET",
                                UpdateTargetId = "tableDiv"
                            })
                        <i class="fa fa-fw fa-sort"></i>
                    </div>
                </th>
                <th>
                    <div class="table_cell">
                        @Ajax.ActionLink("Navn og Type", "UpdateIndex",
                            new
                            {
                                sortColumn = Html.DisplayNameFor(model => model.NameAndType),
                                sortOrder = ViewBag.newSortOrderForNameAndType ?? "ASC",
                                searchParameter = ViewBag.searchParameter
                            },
                            new AjaxOptions
                            {
                                HttpMethod = "GET",
                                UpdateTargetId = "tableDiv"
                            })
                        <i class="fa fa-fw fa-sort"></i>
                    </div>
                </th>
                <th>
                    <div class="table_cell">
                        Valg
                    </div>
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NameAndType)
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary btn-sm m-0" onclick="location.href='@Url.Action("Edit","Equipments",new { id = item.Id })'">Rediger</button>
                        <button type="button" class="btn btn-info btn-sm m-0" onclick="location.href='@Url.Action("Details","Equipments",new { id = item.Id })'">Detaljer</button>
                        <button type="button" class="btn btn-danger btn-sm m-0" onclick="location.href='@Url.Action("Delete","Equipments",new { id = item.Id })'">Slett</button>
                    </td>
                </tr>
            }

        </table>
        <br />

        var pagedList = Model as PagedList.IPagedList<BachelorProject.Models.Equipment>;
        <p>Side  @(pagedList.PageCount < pagedList.PageNumber ? 0 : pagedList.PageNumber) av @pagedList.PageCount </p>
     

        @Html.PagedListPager(pagedList,
                                     page => Url.Action("UpdateIndex", "Equipments",
                                        new
                                        {
                                            page,
                                            searchParameter = ViewBag.searchParameter,
                                            sortColumn = ViewBag.sortColumn,
                                            sortOrder = ViewBag.sortOrder
                                        }),
                                        PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                                        new AjaxOptions()
                                        {
                                            HttpMethod = "GET",
                                            UpdateTargetId = "tableDiv"
                                        }))
    }